// Dati iniziali (seed). Vengono inseriti in PostgreSQL al primo avvio se le
// tabelle sono vuote. Dopo il seed, la fonte di verità è il database e i
// contenuti si gestiscono dal pannello /admin.

import type { Comunicazione, Servizio } from "@/types";

export const seedComunicazioni: Comunicazione[] = [
  {
    id: "uff-001",
    tipo: "ufficiale",
    titolo: "Aggiornamento del piano welfare aziendale 2026",
    estratto:
      "Da luglio entrano in vigore i nuovi benefit: buoni pasto maggiorati e fondo sanitario integrativo.",
    corpo:
      "A partire dal 1° luglio 2026 il piano welfare viene esteso a tutti i dipendenti con contratto a tempo indeterminato. I dettagli operativi e le modalità di adesione saranno disponibili nel portale HR.",
    autore: "Ufficio Risorse Umane",
    data: "2026-06-12",
    categoria: "Risorse Umane",
    inEvidenza: true,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "uff-002",
    tipo: "ufficiale",
    titolo: "Manutenzione programmata dei sistemi gestionali",
    estratto:
      "Sabato 21 giugno, dalle 22:00 alle 02:00, i gestionali ERP e CRM non saranno raggiungibili.",
    corpo:
      "L'intervento di aggiornamento infrastrutturale richiederà il fermo temporaneo dei sistemi. Si raccomanda di salvare il proprio lavoro entro le 21:45.",
    autore: "IT Operations",
    data: "2026-06-11",
    categoria: "IT",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "uff-003",
    tipo: "ufficiale",
    titolo: "Nuova policy di sicurezza informatica",
    estratto:
      "Obbligatoria l'autenticazione a due fattori (MFA) per tutti gli accessi entro fine mese.",
    corpo:
      "Per rafforzare la protezione dei dati aziendali viene introdotta la MFA su tutti i servizi. Le istruzioni di attivazione sono disponibili nella Dashboard Strumenti.",
    autore: "Security Team",
    data: "2026-06-09",
    categoria: "Sicurezza",
    inEvidenza: true,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "uff-004",
    tipo: "ufficiale",
    titolo: "Risultati del primo semestre e obiettivi Q3",
    estratto:
      "La Direzione condivide i risultati del semestre e le priorità per il prossimo trimestre.",
    corpo:
      "Il fatturato del semestre è in crescita del 12% rispetto al 2025. La presentazione completa sarà discussa nella riunione plenaria del 25 giugno.",
    autore: "Direzione Generale",
    data: "2026-06-05",
    categoria: "Direzione",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "noff-001",
    tipo: "non_ufficiale",
    titolo: "Torneo di calcetto aziendale ⚽",
    estratto:
      "Cerchiamo squadre per il torneo del venerdì sera! Iscrizioni aperte fino al 20 giugno.",
    corpo:
      "Ritrovo al campo vicino alla sede. Servono almeno 6 squadre. Scrivete sul canale #sport per organizzarvi!",
    autore: "Marco Bianchi",
    data: "2026-06-13",
    categoria: "Eventi",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "noff-002",
    tipo: "non_ufficiale",
    titolo: "Gruppo d'acquisto frutta e verdura bio",
    estratto:
      "Chi si unisce all'ordine settimanale? Consegna in ufficio il mercoledì.",
    corpo:
      "Stiamo organizzando un gruppo d'acquisto con un produttore locale. Più siamo, più conveniente diventa. Dettagli nei commenti.",
    autore: "Giulia Verdi",
    data: "2026-06-12",
    categoria: "Generale",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "noff-003",
    tipo: "non_ufficiale",
    titolo: "Consigli di lettura per l'estate 📚",
    estratto: "Apriamo un thread per condividere i libri da mettere in valigia.",
    corpo:
      "Dai romanzi ai saggi di management: condividete i vostri preferiti e creiamo una lista comune da appendere in sala relax.",
    autore: "Luca Rossi",
    data: "2026-06-10",
    categoria: "Generale",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
  {
    id: "noff-004",
    tipo: "non_ufficiale",
    titolo: "Aperitivo di benvenuto ai nuovi colleghi 🍹",
    estratto:
      "Giovedì 19 giugno dalle 18:30 diamo il benvenuto al team che si è unito questo mese.",
    corpo:
      "Ci vediamo al bar all'angolo. Un'occasione informale per conoscersi. Offre l'azienda il primo giro!",
    autore: "Sara Neri",
    data: "2026-06-08",
    categoria: "Eventi",
    inEvidenza: false,
    promemoriaData: null,
    eventoData: null,
    eventoOraInizio: null,
    eventoOraFine: null,
    eventoLuogo: null,
    evidenzaFine: null,
    commentiAbilitati: false,
    sondaggioId: null,
    proceduraId: null,
    moduloId: null,
    guidaId: null,
    creatoDa: null,
    visualizzazioni: 0,
  },
];

export const seedServizi: Servizio[] = [
  {
    id: "srv-001",
    nome: "Portale HR",
    descrizione: "Buste paga, ferie, permessi e richieste al personale.",
    url: "https://hr.azienda.local",
    icona: "👥",
    categoria: "Risorse Umane",
    stato: "attivo",
  },
  {
    id: "srv-002",
    nome: "Help Desk IT",
    descrizione: "Apri un ticket per problemi tecnici e richieste hardware.",
    url: "https://helpdesk.azienda.local",
    icona: "🛠️",
    categoria: "IT",
    stato: "attivo",
  },
  {
    id: "srv-003",
    nome: "Prenotazione Sale",
    descrizione: "Prenota sale riunioni e postazioni in smart working.",
    url: "https://sale.azienda.local",
    icona: "📅",
    categoria: "Facility",
    stato: "attivo",
  },
  {
    id: "srv-004",
    nome: "Rimborsi Spese",
    descrizione: "Carica scontrini e gestisci le note spese di trasferta.",
    url: "https://spese.azienda.local",
    icona: "🧾",
    categoria: "Amministrazione",
    stato: "manutenzione",
  },
  {
    id: "srv-005",
    nome: "Knowledge Base",
    descrizione: "Documentazione, procedure e guide operative aziendali.",
    url: "https://wiki.azienda.local",
    icona: "📚",
    categoria: "Documentazione",
    stato: "attivo",
  },
  {
    id: "srv-006",
    nome: "VPN Aziendale",
    descrizione: "Accesso remoto sicuro alla rete interna dell'azienda.",
    url: "https://vpn.azienda.local",
    icona: "🔐",
    categoria: "IT",
    stato: "offline",
  },
];
